### ISSUE TITLE
Build error on ESP32S3

### ISSUE THREAD

**Issue by jrr** [ESP32Async/ESPAsyncWebServer#355]
### Platform

ESP32

### IDE / Tooling

PlatformIO

### What happened?

In a platformio project targeting `board = esp32s3_n16r8`, a recent ESPAsyncWebServer version update provoked this new build error:

```
.pio/libdeps/app/ESPAsyncWebServer/src/WebHandlers.cpp: In member function 'virtual void AsyncStaticWebHandler::handleRequest(AsyncWebServerRequest*)':
.pio/libdeps/app/ESPAsyncWebServer/src/WebHandlers.cpp:241:34: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'uint32_t' {aka 'unsigned int'} [-Werror=format=]
     snprintf(etag, sizeof(etag), "%08lx", etagValue);
                                  ^~~~~~~  ~~~~~~~~~
cc1plus: some warnings being treated as errors
*** [.pio/build/app/lib2bb/ESPAsyncWebServer/WebHandlers.cpp.o] Error 1
```

It looks like it was probably introduced in #303 .

Compiler version:
```
~/.platformio/packages/toolchain-xtensa-esp32s3/bin/xtensa-esp32s3-elf-g++ --version
xtensa-esp32s3-elf-g++ (crosstool-NG esp-2021r2-patch5) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

When I have some I'll try to contribute a repro and/or fix.

### Stack Trace

 n/a

### Minimal Reproductible Example (MRE)

 - create a platformio project targeting `esp32s3_n16r8`
 - add `ESP32Async/ESPAsyncWebServer@3.9.2`
 - `pio run`

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of ESPAsyncWebServer (and AsyncTCP for ESP32).
