### ISSUE TITLE
Issue with 3.4.0 with ESP-IDF & arduino-esp32

### ISSUE THREAD

**Issue by atfox98** [ESP32Async/ESPAsyncWebServer#161]
### IDE / Tooling

ESP-IDF

### What happened?

Skeleton project no longer builds with 3.4.0. I suspect it has something to do with ESP32Async/AsyncTCP#47.

### Stack Trace

```
Compilation failed because AsyncEventSource.cpp (in "esp32async__espasyncwebserver" component) includes Arduino.h, provided by espressif__arduino-esp32 component(s).
However, espressif__arduino-esp32 component(s) is not in the requirements list of "esp32async__espasyncwebserver".
To fix this, add espressif__arduino-esp32 to REQUIRES list of idf_component_register call in project/managed_components/esp32async__espasyncwebserver/CMakeLists.txt.
```

### Minimal Reproductible Example (MRE)

Create the arduino-esp32 hello_world project with the following command:
```
idf.py create-project-from-example "espressif/arduino-esp32:hello_world"
```

In `main/idf_component.yml`, paste the following:

```
dependencies:
  espressif/arduino-esp32: ^3.2.0
  esp32async/espasyncwebserver: ^3.7.6
  esp32async/asynctcp: 3.3.8 
```
Building the project like this works.

To reproduce the issue, change the asynctcp dependency in `idf-component.yml` to 3.4.0:
```
dependencies:
  espressif/arduino-esp32: ^3.2.0
  esp32async/espasyncwebserver: ^3.7.6
  esp32async/asynctcp: 3.4.0
```
The project will now no longer build.

My quick try to band-aid fix was to add the following to CMakeLists.txt
```
if (CONFIG_ENABLE_ARDUINO_DEPENDS)
    set(COMPONENT_REQUIRES "arduino-esp32")
endif()
```
...but in that case it had a different error (missing esp_timer.h/esp_timer component). Adding esp_timer to the COMPONENT_REQUIRES did not solve this, so you are now reading this issue instead of a PR ;-)

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of AsyncTCP.

**Comment by mathieucarbou** [comment]
Moved issue to the right project.

**Comment by mathieucarbou** [comment]
> > I didn't know the WS war relying on AsyncTCP to source its direct dependencies ;-) Let's fix that.
> 
> Yes. AsyncTCP required Arduino and WS required AsyncTCP so it automatically also required Arduino :)

I totally understand that ;-)
But usually when declaring dependencies of a project, we declare all the dependencies the project is relying on, we do not rely on a transitive dependency to bring something the project needs since dependencies of a transitive dependency are out of control of the project.
WS should have declared a dependency over Arduino from start since it depends on it, and also to avoid any effect in changes in the dependencies of asynctcp ;-)
In other languages like Java / Groovy / Gradle they are able to correctly enforce that and have a way to make dependencies of a transitive lib put in an implementation scope, meaning they are not visible to the project (since only used by the transitive dep), except if part of its api, in which case they are declared with another scope.

dependency declarations is important and has non trivial impacts, sometimes hard to foreseen.

**Comment by mathieucarbou** [comment]
@atfox98 : fixed with ~1 rev:

![Image](https://github.com/user-attachments/assets/b8da27b5-6576-46f1-b79e-073f76b2f0cb)
