### ISSUE TITLE
Compiling issue with 3.7,4

### ISSUE THREAD

**Issue by garrybrook** [ESP32Async/ESPAsyncWebServer#141]
### Platform

ESP32

### IDE / Tooling

Arduino (IDE/CLI)

### What happened?

Uanable to compile with new version 3.7.4 but going back to 3.7.2 it compiles OK
The error code using Arduino IDE version 2 is below.

### Stack Trace

In file included from C:\Users\garry\OneDrive\Garry's Stuff\Documents\Arduino\I2C_Hydroponics_Controller\Final_I2C_Hydroponics_Controller_V9\Final_I2C_Hydroponics_Controller_V9.ino:30:
c:\Users\garry\OneDrive\Garry's Stuff\Documents\Arduino\libraries\ESP_Async_WebServer\src/ESPAsyncWebServer.h: In member function 'tcp_state AsyncWebServer::state() const':
c:\Users\garry\OneDrive\Garry's Stuff\Documents\Arduino\libraries\ESP_Async_WebServer\src/ESPAsyncWebServer.h:1107:50: error: passing 'const AsyncServer' as 'this' argument discards qualifiers [-fpermissive]
     return static_cast<tcp_state>(_server.status());
                                                  ^
In file included from C:\Users\garry\OneDrive\Garry's Stuff\Documents\Arduino\I2C_Hydroponics_Controller\Final_I2C_Hydroponics_Controller_V9\Final_I2C_Hydroponics_Controller_V9.ino:29:
c:\Users\garry\OneDrive\Garry's Stuff\Documents\Arduino\libraries\AsyncTCP\src/AsyncTCP.h:198:13: note:   in call to 'uint8_t AsyncServer::status()'
     uint8_t status();
             ^~~~~~

exit status 1

Compilation error: exit status 1

### Minimal Reproductible Example (MRE)

Compile issue

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of ESPAsyncWebServer (and AsyncTCP for ESP32).
